const fs=require('fs'),vm=require('vm'),crypto=require('crypto'),assert=require('assert');
let clockNow='2026-10-01T08:59:00+07:00';
class FakeDate extends Date{constructor(...args){super(...(args.length?args:[clockNow]));}static now(){return new Date(clockNow).getTime();}}
class Range{constructor(sheet,row,col,nrow,ncol){Object.assign(this,{sheet,row,col,nrow,ncol});}getValues(){return Array.from({length:this.nrow},(_,i)=>Array.from({length:this.ncol},(_,j)=>this.sheet.rows[this.row+i-1]?.[this.col+j-1]??''));}setValues(rows){rows.forEach((r,i)=>r.forEach((v,j)=>{const ri=this.row+i-1,ci=this.col+j-1;this.sheet.rows[ri]??=[];this.sheet.rows[ri][ci]=v;}));return this;}setBackground(){return this;}setFontColor(){return this;}setFontWeight(){return this;}setNumberFormat(){return this;}}
class Sheet{constructor(name){this.name=name;this.rows=[];this.columns=26;}getName(){return this.name;}setName(n){this.name=n;}getLastRow(){let n=this.rows.length;while(n&&!this.rows[n-1]?.some(v=>v!==''&&v!==undefined))n--;return n;}getLastColumn(){return Math.max(0,...this.rows.map(r=>r?.length||0));}getMaxRows(){return 1000;}getMaxColumns(){return this.columns;}insertColumnsAfter(_,n){this.columns+=n;}getRange(...a){return new Range(this,...a);}setFrozenRows(){}}
class Spreadsheet{constructor(){this.sheets=[new Sheet('ชีต1')];this.id='mock-db';}getId(){return this.id;}getUrl(){return 'https://docs.google.com/spreadsheets/d/mock-db/edit';}getName(){return 'Nova.3';}getSheets(){return this.sheets;}getSheetByName(n){return this.sheets.find(s=>s.name===n)||null;}insertSheet(n){const s=new Sheet(n);this.sheets.push(s);return s;}deleteSheet(s){this.sheets=this.sheets.filter(x=>x!==s);}setSpreadsheetTimeZone(){}}
const db=new Spreadsheet(),props=new Map(),cache=new Map(),logs=[];const oldShift=new Sheet('Shifts');oldShift.rows=[['shift_id','name']];db.sheets.push(oldShift);
function thaiFormat(d,_zone,fmt){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return fmt.replace(/'/g,'').replace('yyyy',parts.year).replace('MM',parts.month).replace('dd',parts.day).replace('HH',parts.hour).replace('mm',parts.minute).replace('ss',parts.second).replace('XXX','+07:00');}
const context=vm.createContext({console,Date:FakeDate,Math,JSON,String,Number,Boolean,Set,Object,Array,RegExp,Error,Logger:{log:x=>logs.push(x)},SpreadsheetApp:{getActiveSpreadsheet:()=>db,openById:()=>db,create:()=>db,flush:()=>{}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,v),deleteProperty:k=>props.delete(k)})},LockService:{getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})},CacheService:{getScriptCache:()=>({put:(k,v)=>cache.set(k,v),get:k=>cache.get(k)||null,remove:k=>cache.delete(k)})},Utilities:{getUuid:()=>crypto.randomUUID(),computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()].map(v=>v>127?v-256:v),DigestAlgorithm:{SHA_256:'SHA_256'},formatDate:thaiFormat},ContentService:{MimeType:{JSON:'json'},createTextOutput:x=>({text:x,setMimeType(){return this;}})}});
for(const f of ['Setup','Util','Code','Attendance','Leave','Users','Face','Calendar'])vm.runInContext(fs.readFileSync(`apps-script/${f}.gs`,'utf8'),context,{filename:f+'.gs'});
const call=(action,payload={},token='')=>JSON.parse(vm.runInContext('doPost',context)({postData:{contents:JSON.stringify({action,payload,token})}}).text);
const location={latitude:13.638781660954331,longitude:100.39297630086362,accuracy:10};
const scan=(descriptor,token='')=>{const identified=call(token?'identifyFace':'publicIdentify',{descriptor,location},token);assert(identified.ok,identified.error);const result=call(token?'confirmFace':'publicConfirm',{pendingToken:identified.data.pendingToken,location},token);assert(result.ok,result.error);assert(!call(token?'confirmFace':'publicConfirm',{pendingToken:identified.data.pendingToken,location},token).ok);return result;};
const setup=vm.runInContext('setupAll()',context);assert(setup.ok);
assert.strictEqual(vm.runInContext("novaShiftOvertime_('2026-10-02','07:41','18:16',{'เวลาเริ่ม':'09:00','เวลาสิ้นสุด':'18:00'})",context),0.27);
assert.strictEqual(vm.runInContext("novaShiftOvertime_('2026-10-02','07:41','17:59',{'เวลาเริ่ม':'09:00','เวลาสิ้นสุด':'18:00'})",context),0);assert(db.getSheetByName('Attendance'));assert(db.getSheetByName('Accounts'));assert.strictEqual(db.getSheetByName('Attendance').getRange(1,1,1,15).getValues()[0][0],'ชื่อพนักงาน');
const owner=call('login',{userId:'OWNER',pin:setup.ownerPin});assert(owner.ok,owner.error);const ot=owner.data.token;
const added=call('saveEmployee',{userId:'NV001',name:'ทดสอบ ระบบ',nickname:'ทดสอบ',shiftId:'NORMAL',role:'employee'},ot);assert(added.ok,added.error);
const manager=call('saveEmployee',{userId:'MGR01',name:'หัวหน้าแผนก',nickname:'หัวหน้า',shiftId:'NORMAL',role:'manager'},ot);assert(manager.ok,manager.error);
const managerLogin=call('login',{userId:'MGR01',pin:manager.data.pin});assert(managerLogin.ok);
assert(call('updateEmployee',{userId:'NV001',name:'ทดสอบ ระบบ',nickname:'ทดสอบ',department:'ขาย',shiftId:'NORMAL',role:'employee'},managerLogin.data.token).ok);
const emp=call('login',{userId:'NV001',pin:added.data.pin});assert(emp.ok,emp.error);const et=emp.data.token;
assert(!call('saveSettings',{'OT 1.5x':2},et).ok);
const descriptor=Array.from({length:128},(_,i)=>i===0?0.5:0);
assert(!call('clockIn',{descriptor},et).ok);
assert(!call('enrollFace',{userId:'NV001',consent:true,descriptor},et).ok);
assert(call('enrollFace',{userId:'NV001',consent:true,descriptor},ot).ok);
assert(db.getSheetByName('FaceTemplates').getLastRow()===2);
assert(!props.has('NOVA_FACE_NV001'));
assert(!call('clockIn',{descriptor:Array.from({length:128},(_,i)=>i===1?0.5:0)},et).ok);
const publicIn=scan(descriptor);assert(publicIn.ok,publicIn.error);assert.strictEqual(publicIn.data.action,'clockIn');
assert(!call('clockIn',{descriptor},et).ok);
assert.strictEqual(call('bootstrap',{},ot).data.attendance[0].late,0);
clockNow='2026-10-01T12:00:00+07:00';
const out=scan(descriptor,et);assert(out.ok,out.error);
const secondIn=scan(descriptor);assert(secondIn.ok,secondIn.error);assert.strictEqual(secondIn.data.action,'clockIn');assert.strictEqual(secondIn.data.late,0);
clockNow='2026-10-01T14:00:00+07:00';const secondOut=scan(descriptor);assert(secondOut.ok,secondOut.error);assert.strictEqual(secondOut.data.action,'clockOut');
clockNow='2026-10-02T09:05:00+07:00';const nextDay=scan(descriptor,et);assert(nextDay.ok,nextDay.error);assert.strictEqual(nextDay.data.action,'clockIn');
assert.strictEqual(call('bootstrap',{},ot).data.attendance[2].late,5);
clockNow='2026-10-02T13:00:00+07:00';const nextOut=scan(descriptor,et);assert(nextOut.ok,nextOut.error);assert.strictEqual(nextOut.data.action,'clockOut');
const row=call('bootstrap',{},ot).data.attendance[0];assert(row&&row.checkIn&&row.checkOut);
assert(call('editAttendance',{id:row.id,date:row.date,checkIn:row.checkIn,checkOut:row.checkOut,late:row.late,shift:row.shift,ot:row.ot,reason:'แก้เวลาทดสอบ'},ot).ok);
assert(call('reviewAttendance',{id:row.id,status:'อนุมัติ'},ot).ok);
const leave=call('requestLeave',{typeId:'ANNUAL',start:'2026-10-01',end:'2026-10-01',days:1,reason:'ธุระ'},et);assert(leave.ok,leave.error);
assert(!call('requestLeave',{typeId:'ANNUAL',start:'2026-10-01',end:'2026-10-01',days:1,reason:'ซ้ำ'},et).ok);
assert(call('updateLeave',{id:leave.data.id,typeId:'ANNUAL',start:'2026-10-01',end:'2026-10-02',days:2,reason:'แก้วันลา'},et).ok);
assert(!call('reviewLeave',{id:leave.data.id,status:'อนุมัติ'},et).ok);
assert(call('reviewLeave',{id:leave.data.id,status:'อนุมัติ'},ot).ok);
assert(call('cancelLeave',{id:leave.data.id},et).ok);
assert(call('saveLeaveType',{id:'PERSONAL',name:'ลากิจ',days:8,paid:true,status:'ใช้งาน'},ot).ok);
assert(call('saveLeaveType',{id:'WEDDING',name:'ลาแต่งงาน',days:3,paid:false,status:'ปิดใช้งาน'},ot).ok);
assert(!call('requestLeave',{typeId:'WEDDING',start:'2026-11-01',end:'2026-11-01',days:1},et).ok);
assert(!call('saveLeaveType',{id:'ANNUAL',name:'ลาพักผ่อน',days:6,paid:true,status:'ใช้งาน'},ot).ok);
assert(!call('saveLeaveType',{id:'ANNUAL',name:'ลาพักร้อน',days:6,paid:true,status:'ใช้งาน'},et).ok);
assert(!call('requestLeave',{typeId:'ANNUAL',start:'2026-02-31',end:'2026-02-31',days:1},et).ok);
assert(call('adjustAttendance',{id:row.id,reason:'ทดสอบ',ot:{'1.0':25,'1.5':0,'2.0':0,'3.0':0}},ot).ok);
assert(call('saveSettings',{'OT 1.5x':2},ot).ok);
assert(!call('saveSettings',{'OT 1.5x':99},ot).ok);
const dayOff=call('requestDayOff',{userId:'NV001',date:'2026-10-02',note:'หยุด'},et);assert(dayOff.ok,dayOff.error);
assert.strictEqual(dayOff.data.status,'รออนุมัติ');
assert(call('updateDayOff',{userId:'NV001',oldDate:'2026-10-02',date:'2026-10-03',note:'เปลี่ยนวัน'},et).ok);
assert(!call('reviewDayOff',{userId:'NV001',date:'2026-10-02',status:'อนุมัติ'},ot).ok);
assert(!call('requestDayOff',{userId:'MGR01',date:'2026-10-03'},et).ok);
assert(!call('reviewDayOff',{userId:'NV001',date:'2026-10-03',status:'อนุมัติ'},et).ok);
assert(call('reviewDayOff',{userId:'NV001',date:'2026-10-03',status:'อนุมัติ'},ot).ok);
assert(call('bootstrap',{},ot).data.calendar.daysOff.some(r=>r.employeeId==='NV001'));
assert(call('cancelDayOff',{userId:'NV001',date:'2026-10-03'},et).ok);
assert(call('saveSettings',{'Target Latitude':13.7,'Target Longitude':100.5,'Allowed Radius (KM)':1},ot).ok);
assert(!call('resetEmployeePin',{userId:'OWNER'},et).ok);
assert(call('changePin',{oldPin:added.data.pin,newPin:'24681357'},et).ok);
assert(!call('bootstrap',{},et).ok);
const relog=call('login',{userId:'NV001',pin:'24681357'});assert(relog.ok);
assert(call('resetEmployeePin',{userId:'NV001'},ot).ok);
assert(!call('bootstrap',{},relog.data.token).ok);
assert(call('ping').ok);
assert(call('revokeFace',{userId:'NV001',reason:'ทดสอบการลบ'},ot).ok);
assert.strictEqual(db.getSheetByName('FaceTemplates').getRange(2,2,1,1).getValues()[0][0],'');
assert(!call('clockIn',{descriptor},relog.data.token).ok);
assert(call('deleteEmployee',{userId:'NV001',reason:'เลิกจ้างทดสอบ'},ot).ok);
assert(!call('login',{userId:'NV001',pin:'24681357'}).ok);
clockNow='2026-10-03T00:00:00+07:00';assert.strictEqual(vm.runInContext("novaClockWindow_('in')",context),'00:00');
clockNow='2026-10-03T23:59:00+07:00';assert.strictEqual(vm.runInContext("novaClockWindow_('out')",context),'23:59');
vm.runInContext("novaAppend_('FaceTemplateIndex',{'รหัสพนักงาน':'OLD01','ลงทะเบียนเมื่อ':'2026-09-30','ลงทะเบียนโดย':'OWNER','สถานะ':'ใช้งาน'})",context);
props.set('NOVA_FACE_OLD01',JSON.stringify(descriptor));
assert.strictEqual(vm.runInContext('setupAll()',context).ownerPin,'(PIN เดิมยังใช้งานอยู่)');
assert(db.getSheetByName('FaceTemplates').getLastRow()===3);
assert(!props.has('NOVA_FACE_OLD01'));
assert.strictEqual(db.getSheetByName('Accounts').getLastRow(),4);
assert.strictEqual(db.getSheetByName('Shifts').getLastRow(),3);
assert.strictEqual(db.getSheetByName('Shifts').getRange(2,3,1,1).getValues()[0][0],'MORNING');
console.log('PASS setup, login, roles, employee, clock, review, leave, repeat setup');
